### ISSUE TITLE
Calls to `login` in client scripts specify unused argument `login_type`

### ISSUE THREAD

**Issue by aoles** [PondiB/openeogdalcubes#3]
Hi,
when running the sample scripts from `examples` I've experienced the following error:

```
Error in login(user = "user", password = "password", login_type = "basic") : 
  unused argument (login_type = "basic")
```

Removing the argument  `login_type` from the call to `login` seems to resolve the issue.

Cheers,
Andrzej

**Comment by PondiB** [comment]
Hi Andrzej,

Thanks for letting me know. You can do a pull request on it. I believe the OpenEO R client has been updated on CRAN.

**Comment by aoles** [comment]
Thanks Brain! Indeed, according to [release notes](https://open-eo.github.io/openeo-r-client/news/index.html#changed-1-2-0) `login_type` argument to `login` has been removed in **openeo** v1.2.0.

**Comment by PondiB** [comment]
Cool, I will also need to investigate the other issues as I mainly used openeo v1.0.0 specifications and extended the exploration earlier done by someone at Institute for Geoinformatics Münster. There were no issues encountered when using R-client 1.1.0
