### ISSUE TITLE
Error when executing R-Client-truecolors-newyork.R example

### ISSUE THREAD

**Issue by aoles** [PondiB/openeogdalcubes#5]
Hi,

When I try running **R-Client-truecolors-newyork.R** against a local instance of openeocubes server after ca. 40s of processing time I get the following error messages in the client and on the server, respectively. The other two scripts from **examples/** work fine. Any idea what could be the issue? Cheers!

Client:
```
HTTP 500 Internal Server Error.
• SERVER-ERROR: one or more worker processes failed to compute data cube chunks
```

Server:
```
Killed
[ERROR] worker process #1 returned 137
```

**Comment by PondiB** [comment]
I am doing some updates and carrying out tests. I have not encountered this now and so I will close it.
